MindTickets/WebApp-MindTickets/Controllers/GestorDashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace WebApp_MindTickets.Controllers
{
    //[Authorize(Roles = "Gestor")]
    public class GestorDashboardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult PerfilGestor()
        {
            return View();
        }
        public IActionResult Dashboard()
        {
            return View();
        }

        public IActionResult Events() 
        {
            return View();
        }

        public IActionResult GProfile()
        {
            return View();
        }

        public IActionResult FinanceReport()
        {
            return View();
        }
		public IActionResult CreateEvent()
		{
			return View();
		}

        public IActionResult CreateEvents()
        {
            return View();
        }

		public IActionResult RetrieveAllEvents()
		{
			return View();
		}
		public IActionResult SelectEvent()
		{
			return View();
		}
		public IActionResult StageSeat()
		{
			return View();
		}
	}
}

MindTickets/WebApp-MindTickets/Controllers/UserDashboardController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace WebApp_MindTickets.Controllers
{
    public class UserDashboardController : Controller
    {
        //[Authorize(Roles = "Cliente")]
        public IActionResult Perfil()
        {
            return View();
        }

        public IActionResult Dashboard() 
        {
            return View();
        }

        public IActionResult MyEvents() {
            return View();
        }

        public IActionResult EventHistory()
        {
            return View();
        }

        public IActionResult Reports() 
        {
            return View();
        }

        public IActionResult Test()
        {
            return View();
        }

        public IActionResult TemplateTickets()
        {
            return View();
        }

    }
}

MindTickets/WebApp-MindTickets/Views/Shared/_Gestor.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <!-- Styles -->
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.rtl.min.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.rtl.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/v/dt/dt-1.13.5/datatables.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">  
    <link href="~/css/dashboardadmin.css" rel="stylesheet" />
    @await RenderSectionAsync("Styles",required:false)
</head>


<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="#">
                <div class="sidebar-brand-icon">
                    <i class="bi bi-window-fullscreen"></i>
                </div>
                <div class="sidebar-brand-text mx-3">MindTickets</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("GProfile","GestorDashboard")">
                    <i class="bi bi-person-vcard"></i>
                    <span>Perfil</span>
                </a>
            </li>

            <!-- Nav Item - Administración Collapse Menu -->

            <li class="nav-item">
                <a class="nav-link collapsed" href="@Url.Action("Dashboard","GestorDashboard")">
                    <i class="bi bi-person-gear"></i>
                    <span>Dashboard</span>
                </a>
            </li>


            <li class="nav-item">
                <a class="nav-link collapsed" href="@Url.Action("Events","GestorDashboard")" >
                    <i class="bi bi-person-gear"></i>
                    <span>Eventos</span>
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link collapsed" href="@Url.Action("FinanceReport","GestorDashboard")">
                    <i class="bi bi-people-fill"></i>
                    <span>Reportes</span>
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link collapsed" href="@Url.Action("HomePage","Home")">
                    <i class="bi bi-people-fill"></i>
                    <span>Home</span>
                </a>
            </li>
            
        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="@Url.Action("GProfile","GestorDashboard")" id="userDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small" id="display-name-user"></span>
                                <img class="img-profile rounded-circle" id="profile-picture"
                                     src="">
                            </a>                           
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                <div class="container-fluid">
                    @RenderBody()
                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2023</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>

    @*
    <!-- End of Page Wrapper -->
    <!-- Bootstrap core JavaScript-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>
    *@

    <!-- Custom scripts for all pages-->
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    <script src="~/js/controlactions.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdn.datatables.net/v/dt/dt-1.13.5/datatables.min.js"></script>

    <script src="https://upload-widget.cloudinary.com/global/all.js"></script>
    <script src="~/js/dashboardgestor.js"></script>    
    @await RenderSectionAsync("Scripts",required:false)
</body>
</html>

@* Important Section


*@

MindTickets/WebApp-MindTickets/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["MindsTickets"] - WebApp</title>
	<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
	<!--<link rel="stylesheet" href="~/WebApp.styles.css" asp-append-version="true" />-->

	<link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
	<link href="~/lib/bootstrap/dist/css/bootstrap.rtl.min.css" rel="stylesheet" />
	<link href="~/lib/bootstrap/dist/css/bootstrap.rtl.css" rel="stylesheet" />
	<link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />

	<!-- Scripts -->

	<script src="~/lib/jquery/dist/jquery.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
	<script src="~/js/controlactions.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
	<!-- DataTables -->
	<link href="https://cdn.datatables.net/v/dt/dt-1.13.5/datatables.min.css" rel="stylesheet" />
	<script src="https://cdn.datatables.net/v/dt/dt-1.13.5/datatables.min.js"></script>
	@await RenderSectionAsync("Styles",required:false)

</head>
<body>
	<nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
		<div class="container-fluid">
			<a class="navbar-brand" href="@Url.Action("HomePage","Home")"><img class="img-Logo" src="~/images/logotipo mindstickets dark.png" /></a>
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarColor01">
				<ul class="navbar-nav me-auto">
					<li class="nav-item">
						<a class="nav-link active" href="@Url.Action("HomePage","Home")">
							<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-house-check-fill" viewBox="0 0 16 16">
								<path d="M8.707 1.5a1 1 0 0 0-1.414 0L.646 8.146a.5.5 0 0 0 .708.708L8 2.207l6.646 6.647a.5.5 0 0 0 .708-.708L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.707 1.5Z" />
								<path d="m8 3.293 4.712 4.712A4.5 4.5 0 0 0 8.758 15H3.5A1.5 1.5 0 0 1 2 13.5V9.293l6-6Z" />
								<path d="M12.5 16a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7Zm1.679-4.493-1.335 2.226a.75.75 0 0 1-1.174.144l-.774-.773a.5.5 0 0 1 .708-.707l.547.547 1.17-1.951a.5.5 0 1 1 .858.514Z" />
							</svg>
							Home
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="@Url.Action("RetrieveAllEvents","GestorDashboard")">
							<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-calendar2-event" viewBox="0 0 16 16">
								<path d="M11 7.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-1z" />
								<path d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5zM2 2a1 1 0 0 0-1 1v11a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V3a1 1 0 0 0-1-1H2z" />
								<path d="M2.5 4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5H3a.5.5 0 0 1-.5-.5V4z" />
							</svg>
							Eventos
						</a>

					</li>
					@if (User.IsInRole("Administrador"))
					{

						<li class="nav-item">
							<a class="nav-link" href="@Url.Action("Dashboard","AdminDashboard")">
								<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bar-chart-fill" viewBox="0 0 16 16">
									<path d="M1 11a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v3a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1v-3zm5-4a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v7a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V7zm5-5a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1h-2a1 1 0 0 1-1-1V2z" />
								</svg>
								Dashboard
							</a>
						</li>
					}

					@if (User.IsInRole("Gestor"))
					{
						<li class="nav-item">
							<a class="nav-link" href="@Url.Action("Dashboard","GestorDashboard")">
								<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bar-chart-fill" viewBox="0 0 16 16">
									<path d="M1 11a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v3a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1v-3zm5-4a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v7a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V7zm5-5a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1h-2a1 1 0 0 1-1-1V2z" />
								</svg>
								Dashboard
							</a>
						</li>
					}

					@if (User.IsInRole("Cliente"))
					{
						<li class="nav-item">
							<a class="nav-link" href="@Url.Action("Dashboard","UserDashboard")">
								<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-bar-chart-fill" viewBox="0 0 16 16">
									<path d="M1 11a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v3a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1v-3zm5-4a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v7a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1V7zm5-5a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1h-2a1 1 0 0 1-1-1V2z" />
								</svg>
								Dashboard
							</a>
						</li>
					}
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
							<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-gear" viewBox="0 0 16 16">
								<path d="M8 4.754a3.246 3.246 0 1 0 0 6.492 3.246 3.246 0 0 0 0-6.492zM5.754 8a2.246 2.246 0 1 1 4.492 0 2.246 2.246 0 0 1-4.492 0z" />
								<path d="M9.796 1.343c-.527-1.79-3.065-1.79-3.592 0l-.094.319a.873.873 0 0 1-1.255.52l-.292-.16c-1.64-.892-3.433.902-2.54 2.541l.159.292a.873.873 0 0 1-.52 1.255l-.319.094c-1.79.527-1.79 3.065 0 3.592l.319.094a.873.873 0 0 1 .52 1.255l-.16.292c-.892 1.64.901 3.434 2.541 2.54l.292-.159a.873.873 0 0 1 1.255.52l.094.319c.527 1.79 3.065 1.79 3.592 0l.094-.319a.873.873 0 0 1 1.255-.52l.292.16c1.64.893 3.434-.902 2.54-2.541l-.159-.292a.873.873 0 0 1 .52-1.255l.319-.094c1.79-.527 1.79-3.065 0-3.592l-.319-.094a.873.873 0 0 1-.52-1.255l.16-.292c.893-1.64-.902-3.433-2.541-2.54l-.292.159a.873.873 0 0 1-1.255-.52l-.094-.319zm-2.633.283c.246-.835 1.428-.835 1.674 0l.094.319a1.873 1.873 0 0 0 2.693 1.115l.291-.16c.764-.415 1.6.42 1.184 1.185l-.159.292a1.873 1.873 0 0 0 1.116 2.692l.318.094c.835.246.835 1.428 0 1.674l-.319.094a1.873 1.873 0 0 0-1.115 2.693l.16.291c.415.764-.42 1.6-1.185 1.184l-.291-.159a1.873 1.873 0 0 0-2.693 1.116l-.094.318c-.246.835-1.428.835-1.674 0l-.094-.319a1.873 1.873 0 0 0-2.692-1.115l-.292.16c-.764.415-1.6-.42-1.184-1.185l.159-.291A1.873 1.873 0 0 0 1.945 8.93l-.319-.094c-.835-.246-.835-1.428 0-1.674l.319-.094A1.873 1.873 0 0 0 3.06 4.377l-.16-.292c-.415-.764.42-1.6 1.185-1.184l.292.159a1.873 1.873 0 0 0 2.692-1.115l.094-.319z" />
							</svg>
						</a>
						<div class="dropdown-menu">
							<a class="dropdown-item" href="@Url.Action("Memberships","Home")">Membresía</a>
							<a class="dropdown-item" href="@Url.Action("Dashboard","GestorDashboard")">Gestor</a>
							<a class="dropdown-item" href="@Url.Action("Dashboard","AdminDashboard")">Administrador</a>
							<a class="dropdown-item" href="@Url.Action("Dashboard","UserDashboard")">Cliente</a>
							<div class="dropdown-divider"></div>
						</div>
					</li>
				</ul>
				<form class="d-flex">
					<input class="form-control me-sm-2" type="search" placeholder="Search">
					<button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
				</form>
			</div>
		</div>
		<div class="collapse navbar-collapse" id="navbarColor01">
			<ul class="navbar-nav me-auto">
				<li class="nav-item">
					<a class="nav-link" asp-page="/UserProfile">
						<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-lines-fill" viewBox="0 0 16 16">
							<path d="M6 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm-5 6s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zM11 3.5a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1h-4a.5.5 0 0 1-.5-.5zm.5 2.5a.5.5 0 0 0 0 1h4a.5.5 0 0 0 0-1h-4zm2 3a.5.5 0 0 0 0 1h2a.5.5 0 0 0 0-1h-2zm0 3a.5.5 0 0 0 0 1h2a.5.5 0 0 0 0-1h-2z" />
						</svg>
						Perfil
					</a>
				</li>
				<li class="nav-item">
					@Html.ActionLink("Cerrar Sesión", "Logout", "Home", new { area = "" }, new { @class = "navbar-brand" })	
				</li>
			</ul>
		</div>
	</nav>
	<div class="container">
		<main role="main" class="pb-3">
			@RenderBody()
		</main>
	</div>
	<div class="Container-chat">
		<a href="/">
			<img class="ChatBot" src="~/images/chat-121.png" />
		</a>
	</div>
	@*
	<footer class="footer-section">
	<div class="menu-footer-section">
	<div class="footer-creds">
	<p>©copyright 2023 - MindsTickets.com - Todos los derechos reservados.- San José, Costa Rica</p>
	</div>
	</div>

	</footer>
	*@
	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>

	@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MindTickets/WebApp-MindTickets/Views/Shared/_User.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <!-- Styles -->
    <link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.rtl.min.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.rtl.css" rel="stylesheet" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="https://cdn.datatables.net/v/dt/dt-1.13.5/datatables.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <link href="~/css/dashboardadmin.css" rel="stylesheet" />
    @await RenderSectionAsync("Styles",required:false)
</head>


<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="#">
                <div class="sidebar-brand-icon">
                    <i class="bi bi-window-fullscreen"></i>
                </div>
                <div class="sidebar-brand-text mx-3">MindTickets</div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item">
                <a class="nav-link" href="@Url.Action("Perfil","UserDashboard")">
                    <i class="bi bi-person-vcard"></i>
                    <span>Perfil</span>
                </a>
            </li>

            <!-- Nav Item - Administración Collapse Menu -->

            <li class="nav-item">
                <a class="nav-link collapsed" href="@Url.Action("Dashboard","UserDashboard")">
                    <i class="bi bi-speedometer2"></i>
                    <span>Dashboard</span>
                </a>                
            </li>


            <li class="nav-item">
                <a class="nav-link collapsed" href="@Url.Action("MyEvents","UserDashboard")">
                    <i class="bi bi-calendar-week"></i>
                    <span>Mis Eventos</span>
                </a>                
            </li>

            <li class="nav-item">
                <a class="nav-link collapsed" href="@Url.Action("EventHistory","UserDashboard")" >
                    <i class="bi bi-calendar-week"></i>
                    <span>Historial</span>
                </a>
            </li>

            <!-- Nav Item - Usuarios Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="@Url.Action("Reports","UserDashboard")">
                    <i class="bi bi-bar-chart-line"></i>
                    <span>Reportes</span>
                </a>                
            </li>
            <!-- Nav Item - Usuarios Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="@Url.Action("Logout","Home")" >
                    <i class="bi bi-x-circle"></i>
                    <span>Cerrar sesión</span>
                </a>
            </li>
        </ul>
        <!-- End of Sidebar -->
        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="@Url.Action("Perfil","UserDashboard")" id="userDropdown" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small" id="display-name-user"></span>
                                <img class="img-profile rounded-circle" id="profile-picture"
                                     src="">
                            </a>                            
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->
                <!-- Begin Page Content -->
                <div class="container-fluid">
                    @RenderBody()
                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2023</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>

    @*
    <!-- End of Page Wrapper -->
    <!-- Bootstrap core JavaScript-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>
    *@

    <!-- Custom scripts for all pages-->
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    <script src="~/js/controlactions.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdn.datatables.net/v/dt/dt-1.13.5/datatables.min.js"></script>        
    
    @*<script src="~/js/dashboardclient.js"></script>*@
    <script src="https://upload-widget.cloudinary.com/global/all.js"></script>
    @await RenderSectionAsync("Scripts",required:false)
</body>
</html>

@* Important Section


*@